### ISSUE TITLE
Make publication via RPKI repos optional

### ISSUE THREAD

**Issue by benmaddison** [job/draft-rpki-checklists#1]
https://github.com/job/draft-rpki-checklists/blob/64d38fafe4d66617efdfa4d9421ca79de150e5d4/draft-spaghetti-sidrops-rpki-rsc.xml#L80

There are use cases where publication in the RPKI would be useful:
- parties that have no direct relationship can communicate assertions without an alternate means of transport
- assertions that are intended to be "public" can be published in a single location
- revocation works as usual

doing this probably just requires:
"SIA is optional, and only present when the RSC appears on the MFT of the issuing CA"

Thoughts?

**Comment by job** [comment]
> There are use cases where publication in the RPKI would be useful:
> 
>     * parties that have no direct relationship can communicate assertions without an alternate means of transport

If the parties have no direct relationship, then they have no need for RSC (which facilitates private business to business processes). In the current draft `rpki-rsc-01` only 'local' files can be referenced, making the semantics incompatible with publication. (But I note that your suggestion for URIs changes this)

>     * assertions that are intended to be "public" can be published in a single location

Can we come up with robust non-contrived examples?

>     * revocation works as usual

Revocation already works as usual, if you follow the AIA there will be a CRL on that CA, which covers the subordinate EE embedded in the RSC.

**Comment by job** [comment]
As this concerns local (relative) filenames, no pointer can be established from the a public RSC file to the privately stored files listed on the RSC. This is approached differently in RSU where publication would be permissible
