### ISSUE TITLE
URI instead of file?

### ISSUE THREAD

**Issue by benmaddison** [job/draft-rpki-checklists#2]
https://github.com/job/draft-rpki-checklists/blob/64d38fafe4d66617efdfa4d9421ca79de150e5d4/draft-spaghetti-sidrops-rpki-rsc.xml#L136-L138

Depending on the use case, being able to point to a URI where the signed document can be retrieved may be useful.

E.g. I might want to sign our communities ref document, and put https://as37271.fyi/static/net_info_portal/md/bgp-communities.md in the `file` part.

**Comment by job** [comment]
An interesting idea

I'd make it a new optional section, to help validators whether they should `open()` from the `$CWD` or print a URI for the operator to fetch. Something along these lines (don't worry, I can do the ASN.1!)

```
 URIAndHash ::= SEQUENCE { 
   uri            IA5String, 
   hash            Digest } 
```

This idea would require a section explaining what 'files' are and what 'uris' mean

**Comment by job** [comment]
Or... perhaps we should not make a kitchensink out of RSC... and launch a second draft "RPKI Signed URIs"

This increases the chances of RSC making it to the finish line and getting deployed.

**Comment by job** [comment]
To increase the chances of RSC making it to the finish line, my preference would be to (in a few weeks) launch a second draft "RPKI Signed URIs", which *only* allows full URIs to be listed in the eContent, and can be published in the global RPKI.

RSC == 100% local, RSC itself not published
RSU == 100% remote, RSU optionally published via RPKI repositories

Mixing the two distinct features will hamper progress

OIDs are cheap, we have infinite! Happy to help co-author a URI flavor
