### ISSUE TITLE
Use-case distinguisher field

### ISSUE THREAD

**Issue by benmaddison** [job/draft-rpki-checklists#3]
This goes hand-in-hand with #1 

Say I run a service that allows customers to BYOIP, and I ask them to publish
their "LOA" checklist objects at some know location (possibly the RPKI repo system itself).

I would want an easy way to filter the list of all retrieved objects for the
ones that are intended for my use.

I *could* filter based on the contents of the underlying data (assuming I even
have access to that), but it would be much neater to simply signal the objects
purpose with an opaque identifier in the RSC object itself.

Think RT ext-comms, but for RSC audiences.

The tricky bit is the name-spacing. OIDs with private enterprise numbers could work perhaps?

**Comment by job** [comment]
I don't understand this suggestion... please help! :)
