### ISSUE TITLE
TYPE token in CONTENT-TYPE definition

### ISSUE THREAD

**Issue by benmaddison** [job/draft-rpki-checklists#6]
In:

https://github.com/job/draft-rpki-checklists/blob/bbd1cb2bf0a324ed006cee271b297f18f5211f28/draft-ietf-sidrops-rpki-rsc.xml#L124-L128

The `TYPE` token bamboozles my compiler.

Is this a new addition to the ASN.1 spec? I can't find any example of it's usage elsewhere, nor any definition of what it does.

**Comment by job** [comment]
It seems to me to be an "IETF macro", from the revised RFC 5911 ASN.1
```
  CONTENT-TYPE ::= CLASS {
    &id OBJECT IDENTIFIER UNIQUE,
    &Type OPTIONAL
    } WITH SYNTAX {
    [TYPE &Type] IDENTIFIED BY &id
    }

  ContentType ::= CONTENT-TYPE.&id
```

https://www.rfc-editor.org/rfc/inline-errata/rfc5911.html#btn_2612

**Comment by benmaddison** [comment]
I patched my source modules for https://www.rfc-editor.org/errata/eid2612 and now I can compile with the `TYPE` token present.
Thanks for the pointer...
